/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fibonacci_FibLib */

#ifndef _Included_com_example_fibonacci_FibLib
#define _Included_com_example_fibonacci_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fibonacci_FibLib
 * Method:    javamain
 * Signature: (I[C)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fibonacci_FibLib_javamain
  (JNIEnv *, jclass, jlong, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
